### ISSUE TITLE
Comments on the Publication page (1.2)

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#26]
On pages like [this one](http://portal.lsstdesc.org/Pubs/show_pub.jsp?paperid=66&swgid=4), can you include a 'Last updated' date in addition to the 'Added' field?

I'd recommend moving the 'Brief Summary' box to just below the Title entry.

For draft papers, we also need a way to store the names of the review committee members (and when available links to the page or Discourse entry with the reports and responses.

I'd change 'upload Document' to 'Upload Document' or (maybe better) 'Upload Draft'.  When I click on the link I get taken to a page where I need to select the paper title.  Instead can the system just assume that what I want to do is upload a new draft of the same paper?

When I tried to upload a paper draft I got this message:
> 500 - Internal server error.
> There is a problem with the resource you are looking for, and it cannot be displayed.

I was wondering whether (after I uploaded the draft), the page for that paper would show me a table of the drafts in reverse chronological order (altough I guess with one entry in this case).

**Comment by chee999** [comment]
Here are the replies to the above comments:
Brief Summary:
Brief Summary has been moved to just below the Title entry

Draft Papers:
The option to add/remove reviewers has been added.
 
Upload Document:
Upload Document has been changed to Upload Draft of <paperid>. The upload link takes you to the upload for the specified paper instead of a pick-list of documents.
A table of existing, downloadable drafts is now displayed in reverse chronological order.
