### ISSUE TITLE
What happens to my reason for requesting authorship?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#58]
Will it become my initial contribution statement? That would be efficient: please consider this an enhancement request.
I guess right now though, I would assume that it is simply a message sent to the primary authors, and that I'll be asked for more details about my contribution later (or not, if we decide to just roll with the checkboxes).

**Comment by chee999** [comment]
When you request authorship, the collected information is put into a database and set for mail delivery. The mail script checks every minute and when it finds a request it sends it to the lead authors of the paper. Once the mail has been sent the request is removed from the database.

We came up with this idea since we had to do something with the request. Other ideas are welcome.

**Comment by sethdigel** [comment]
I'd recommend closing this issue because it is covered by others.

**Comment by drphilmarshall** [comment]
Do it, I agree.

**Comment by sethdigel** [comment]
I'd like to close it but I cannot, only Comment.

**Comment by chee999** [comment]
Closing issue.
