### ISSUE TITLE
Notify new authors

### ISSUE THREAD

**Issue by chee999** [LSSTDESC/desc-publications#64]
When a person is added as an author (through the GroupManager groups) it would be nice to send email to that person and copy to the lead authors.

**Comment by sethdigel** [comment]
Yes.  As imagined in #70, it would be desirable if the Lead authors were given a link to a page where they could accept or reject a request - rather than have them manually interact with the Group Manager interface for their paper.

* I'd recommend  including  a field where the  Lead authors could provide some text to be included in the automatically sent  e-mail message.  This field could be left blank but  presumably for rejections it would not.

* For rejected requests, the Project leads and the WG conveners should be cc-ed  on the automatically sent message.

* Suggested format for the message:

Subject:  Re: your request for authorship on "pub-title" (pub-id)

**Re: DESC-NNNN "pub-title"**
Lead authors:  user-full-name, user-full-name

Your request for authorship has been accepted/rejected.  Any feedback from the lead authors is below.

**Comment by sethdigel** [comment]
Charlotte has implemented this - thank you.
