### ISSUE TITLE
Updates to / comments about front page

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/desc-publications#9]
Here are some comments and questions about the front page, which we get as soon as we go to http://portal.lsstdesc.org/Pubs/projects.jsp and log in.

- Some mailing lists have the e-mail address correctly, while others are missing the `@slac.stanford.edu`.  I confirmed that if I click on one of the latter, it opens an e-mail message to e.g. lsst-desc-comb-theory (without the rest of the address).  (Also, should it really be `@listserv.slac.stanford.edu` as it is for most of them?  I didn't know that worked, I thought it had to be `@slac.stanford.edu`)

- At least one of the e-mail addresses is wrong; the CI group uses lsst-desc-comp-infrastruc, not lsst-desc-software.  It would be worth reviewing these to look for more issues.

- Do you need to connect to some database to populate the convener names? Is additional infrastructure needed for that?

**Comment by chee999** [comment]
I've cleaned up the mailing list addresses. The current arrangement is that each working group also has a convener group. For now, any pub board member should be able to add or remove names from either of these
groups in order to get feedback on the system.

**Comment by sethdigel** [comment]
Here are a few questions and comments about the table at http://portal.lsstdesc.org/Pubs/projects.jsp.

* In the first column, ID is the identifying number for the project?  I'd guess so, except I see that several entries have the same Id numbers.  Is that because the stated project belongs to more than one working group?  (Actually, ID = 26 appears 8 times, four for Strong Lensing and four for Large Scale Structure.)

* The Title column is blank - I guess that would be easy to fix

* I'd recommend listing the Work Group(s) column first, and having the projects appear in order by working group.  The ID column probably should go last.

* If the Members column is listing the project leads, I'd change the title to Project Lead(s).  In any case, I would not list all of the members of a Project in this table.

* In the current table, the links from the Members (currently Charlotte Hee and Seth Digel) go to blank entries in the User and Group Manager.

**Comment by chee999** [comment]
I meant to remove the 'projects.jsp' page. It has been replaced with the 'all_projects.jsp' page, which is also
the link that is used in the pull down menu at the top navigation bar.

**Comment by chee999** [comment]
The title now appears and the rearranged the table so that working groups come first, then projects, the state of the project, if it's a key project and a link via id to the project. The project is also linked under its title.

**Comment by chee999** [comment]
The list of all projects is now under all_projects.jsp
