### ISSUE TITLE
SRM Deliverable field

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#95]
In the Project definition page, we need a form box marked "SRM deliverable/activity" that either takes freeform text or (better) provides a drop-down list of deliverable activity names. I imagine the former is easier to set up.  This pub system field is important: it will be the primary connection between the projects being worked on and our plan.

We need to be prepared for that SRM list to change over time, since we are regularly modifying the science roadmap as we go. We will need the ability to adjust all the "srm-item" values in the projects database table to be modified by script.

**Comment by chee999** [comment]
Do you have an enumerated list of values for SRM_Activity?

**Comment by chee999** [comment]
"modified by script" - does that mean a script will need write access to Oracle?

**Comment by chee999** [comment]
Are these examples of SRM activities (I should have checked the SRM doc first)? It looks like they are not just strings but hyperlinks?
1) Software for determining WL requirements
2) Create WL DC1 simulated datasets
3) Software for blinding the shear catalogs

**Comment by drphilmarshall** [comment]
We can make you a CSV file containing deliverable and activity names (titles) - [here's an example](https://drive.google.com/file/d/1L2vXt-GgnIgkmGeb-in1Nuo1M_MHpmkL/view?usp=sharing) that just contains the deliverables (and not the activities). Titles are in column 2. 

"Modified by script": we must expect the CSV file to be updated periodically. In these updates, we can expect a) deliverable names to change, and b) deliverables to be deleted. The number of changes could be large. In general I think such changes to the db should be scripted. Is it not possible to edit Oracle db entries via python script?

The SRM PDF contains hyperrefs to elsewhere in the document. The CSV file above contains the strings we need (and that pub system users should be inputting). 

Thanks!

**Comment by sethdigel** [comment]
@drphilmarshall should filling out this field be mandatory?  That is, can we imagine valid Projects that do not map to the SRM?

**Comment by chee999** [comment]
Can you write the CSV file out to disk under /nfs/farm/g/lsst/?

**Comment by sethdigel** [comment]
I've copied Phil's file to /nfs/farm/g/lsst/u1/DESC_PubBd/srm.WBS.csv

N.B. as Phil indicated earlier in this issue, this file contains only the Deliverables.  He will also want to include the Activities.  So this particular file is only a placeholder.

**Comment by chee999** [comment]
Created the python script that uploads the SRM activities from the nfs file. The actual fields to upload and the format of these fields still need to be sorted out. Once that is done the cronjob can be scheduled to update the activities automatically and displayed as a select list to the user.

**Comment by sethdigel** [comment]
We still need a CSV file from @drphilmarshall that includes all of the deliverables and activities, but that is separate from the implementation.  At that time, this issue can be closed.  

We should not have a cron job picking up new versions of the CSV file.  The file will change very infrequently (on the order of annually), and the changes of the contents are likely to be substantial.  Before switching to a new set of deliverable and activity codes,  someone will need to (manually) define the mapping between the old codes and the new ones, so the already existing entries in the system can be updated.  At that point, the CSV file with the new designators can be uploaded.

**Comment by drphilmarshall** [comment]
While updating the [example project template confluence page](https://confluence.slac.stanford.edu/display/LSSTDESC/Example+Project%3A+Make+a+Copy+and+Edit+It) I realized that projects will often be associated with a research activity and an operations deliverable, and that its possible that a single project will support more than one of each. That leads to two new issues: 1) can we enable multiple deliverables to be selected for any given project? 2) can we separate the deliverables and activities by having two form boxes? I will issue the second of these separately ("Add a separate 'SRM Activities' field"), and edit the title of this thread accordingly. The csv file I gave the link to is therefore the right one for the SRM Deliverable dropdown menu, and so this issue can be closed if:

* [ ] More than one deliverable (or none) can be selected for the project
* [ ] Deliverables are selectable by their _title_ (column 2 of the csv file, example ""Software Framework Implementation")

Thanks for all the scripting, @chee999 ! :-)

**Comment by sethdigel** [comment]
@drphilmarshall should the deliverable titles be listed in any particular order?  Would there be some advantage to listing both the deliverable 'code' and the title together?  That way at least there'd be some sorting according to working group (which is identified in the first part of the code)

**Comment by drphilmarshall** [comment]
The best order is probably the order in the file. TBH this will work best
if the form box knows to auto-filter or auto-complete, so that when you
start typing the list narrows down. I don't know if our form boxes have
that property, I know Google sheets do. Forming a string like "Title (WL,
DC2)" may well be helpful. Should the data file contain that string, or
should the code formulate that string from the data in the data file? I'd
prefer the latter I think.

**Comment by sethdigel** [comment]
> The best order is probably the order in the file. TBH this will work best
if the form box knows to auto-filter or auto-complete, so that when you
start typing the list narrows down. I don't know if our form boxes have
that property, I know Google sheets do. Forming a string like "Title (WL,
DC2)" may well be helpful. Should the data file contain that string, or
should the code formulate that string from the data in the data file? I'd
prefer the latter I think.

I think that the list of options should include the activity ID or deliverable ID, in addition what you propose.  Assembling the strings from the csv files should be straightforward.  This will provide some sensible ordering, and a way to look up items in the SRM.  Otherwise, people would be left to scroll and select from a list of ~200 longish titles with no particularly obvious order.

**Comment by sethdigel** [comment]
> The best order is probably the order in the file. TBH this will work best
if the form box knows to auto-filter or auto-complete, so that when you
start typing the list narrows down. I don't know if our form boxes have
that property, I know Google sheets do. Forming a string like "Title (WL,
DC2)" may well be helpful. Should the data file contain that string, or
should the code formulate that string from the data in the data file? I'd
prefer the latter I think.

I think that the list of options should include the activity ID or deliverable ID, in addition what you propose.  Assembling the strings from the csv files should be straightforward.  This will provide some sensible ordering, and a way to look up items in the SRM.  Otherwise, people would be left to scroll and select from a list of ~200 longish titles with no particularly obvious order.

**Comment by sethdigel** [comment]
Charlotte has the Project information page display the selected deliverables.  Thank you!
